# Generated by Django 3.1 on 2023-11-28 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gamepanel.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=23, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FTP_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(default=gamepanel.models.FTP_User.random_password, max_length=14)),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gamepanel.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('img', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('owner', models.CharField(max_length=200)),
                ('os', models.CharField(max_length=200)),
                ('machine_address', models.GenericIPAddressField(null=True, unique=True)),
                ('ssh_username', models.CharField(max_length=200)),
                ('ssh_password', models.CharField(max_length=200)),
                ('ssh_port', models.PositiveBigIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('img', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Mod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('label', models.CharField(blank=True, max_length=30, null=True)),
                ('img', models.ImageField(blank=True, upload_to='')),
                ('version', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('port', models.CharField(blank=True, max_length=15)),
                ('startup_line', models.CharField(blank=True, max_length=300, null=True)),
                ('max_players', models.CharField(blank=True, max_length=300, null=True)),
                ('map', models.CharField(blank=True, max_length=300, null=True)),
                ('rcon_password', models.CharField(blank=True, max_length=300, null=True)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='offline', max_length=10)),
                ('is_active', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_over', models.DateField(blank=True, null=True)),
                ('ftp_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='server', to='gamepanel.ftp_user')),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gamepanel.game')),
                ('ip_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gamepanel.machine', to_field='machine_address')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servers', to='gamepanel.machine')),
                ('mod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gamepanel.mod')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gamepanel.customer')),
            ],
        ),
    ]
