# Generated by Django 4.2.6 on 2023-12-11 12:31

from django.db import migrations, models
import gamepanel.models


class Migration(migrations.Migration):

    dependencies = [
        ('gamepanel', '0005_rconresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ftp_user',
            name='password',
            field=models.CharField(default=gamepanel.models.FTP_User.random_password, max_length=24),
        ),
    ]
