# Generated by Django 4.2.6 on 2023-12-11 12:44

from django.db import migrations, models
import gamepanel.models


class Migration(migrations.Migration):

    dependencies = [
        ('gamepanel', '0006_alter_ftp_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='ftp_user',
            name='password_label',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='ftp_user',
            name='password',
            field=models.CharField(default=gamepanel.models.FTP_User.random_password, max_length=50),
        ),
    ]
