# Generated by Django 4.2.6 on 2023-12-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamepanel', '0008_plugin'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugin',
            name='category',
            field=models.CharField(blank=True, choices=[('clanwar', 'clanwar'), ('zombieplague', 'zombieplague'), ('surf', 'surf'), ('deathrun', 'deathrun'), ('knifearena', 'knifearena'), ('gungame', 'gungame'), ('deathmatch', 'deathmatch'), ('fy_snow', 'fy_snow'), ('public', 'public')], max_length=300, null=True),
        ),
    ]
