# Generated by Django 4.2.6 on 2023-12-20 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamepanel', '0009_plugin_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='balance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='img',
            field=models.ImageField(blank=True, upload_to='customer-profile-pictures/'),
        ),
        migrations.AddField(
            model_name='customer',
            name='xp',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
