# Generated by Django 4.2.6 on 2023-12-21 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamepanel', '0011_customer_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugin',
            name='description',
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
    ]
