# Generated by Django 4.2.6 on 2023-12-21 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamepanel', '0013_alter_plugin_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plugin',
            name='description',
            field=models.TextField(blank=True, max_length=2500, null=True),
        ),
    ]
