# Generated by Django 4.2.6 on 2023-12-24 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamepanel', '0015_alter_rconresult_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rconresult',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gamepanel.customer'),
        ),
    ]
