# Generated by Django 4.2.6 on 2023-12-27 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamepanel', '0018_remove_rconresult_game_alter_rconresult_user_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='rconresult',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gamepanel.game'),
        ),
    ]
