# Generated by Django 4.2.6 on 2024-01-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamepanel', '0020_remove_customer_password_alter_customer_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='img',
            field=models.ImageField(blank=True, default='user.png', upload_to='customer-profile-pictures/'),
        ),
    ]
