# Generated by Django 4.2.6 on 2024-01-13 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamepanel', '0022_ticket_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='game',
            field=models.CharField(blank=True, choices=[('Counter-Strike 1.6', 'Counter-Strike 1.6'), ('CS2', 'CS2'), ('SA:MP', 'SA:MP'), ('Minecraft', 'Minecraft')], max_length=50, null=True),
        ),
    ]
