# Generated by Django 4.2.6 on 2024-01-13 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamepanel', '0024_ticketmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.ManyToManyField(related_name='conversation_messages', to='gamepanel.ticketmessage')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='gamepanel.ticket')),
            ],
        ),
    ]
