# Generated by Django 4.2.6 on 2024-01-13 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamepanel', '0025_ticketconversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmessage',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_messages', to='gamepanel.ticketconversation'),
        ),
        migrations.AlterField(
            model_name='ticketconversation',
            name='messages',
            field=models.ManyToManyField(related_name='ticket_messages', to='gamepanel.ticketmessage'),
        ),
        migrations.AlterField(
            model_name='ticketconversation',
            name='ticket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_conversation', to='gamepanel.ticket'),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_messages', to='gamepanel.ticket'),
        ),
    ]
