# Generated by Django 4.2.6 on 2024-01-18 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamepanel', '0026_ticketmessage_conversation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='label',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
